// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MudManagement.Server.Db;

#nullable disable

namespace MudManagement.Server.Migrations
{
    [DbContext(typeof(MudDbContext))]
    [Migration("20240627091802_adjustmud_quality_dhft")]
    partial class adjustmud_quality_dhft
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("MudManagement.Server.Models.mud_quality_dhft", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("uuid()");

                    b.Property<string>("benbingbei")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("benbingbi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("benbingbyingen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("benbingen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("benbingkyingen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("bi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("e")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("en")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("erbenbingen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("exi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("fei")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("longitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("qu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("wu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("yinbingbi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("yingen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("zl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("mud_quality_dhft");
                });

            modelBuilder.Entity("MudManagement.Server.Models.mud_quality_jcsx", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("uuid()");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hanshaliang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hanshuilv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("longitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ph")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("youjizhi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("mud_quality_jcsx");
                });

            modelBuilder.Entity("MudManagement.Server.Models.mud_quality_kss", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("uuid()");

                    b.Property<string>("aqms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hacd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hajec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hajmd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hamd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hbsx")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("klms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lhms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("longitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nfsx")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("shs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("yfsx")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("mud_quality_kss");
                });

            modelBuilder.Entity("MudManagement.Server.Models.mud_quality_xdfcw", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("uuid()");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("longitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lys")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("sljw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("slys")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("mud_quality_xdfcw");
                });

            modelBuilder.Entity("MudManagement.Server.Models.mud_quality_zjs", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("uuid()");

                    b.Property<string>("As")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pb")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("hg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("longitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("zn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("mud_quality_zjs");
                });

            modelBuilder.Entity("MudManagement.Server.Models.mud_quality_zysx", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("uuid()");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("longitude")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("zd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("zj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("zl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("zyf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("mud_quality_zysx");
                });

            modelBuilder.Entity("MudManagement.Server.Models.mud_quantity_gqwn", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("uuid()");

                    b.Property<string>("chanliang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("guandaochangdu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("mud_quantity_gqwn");
                });

            modelBuilder.Entity("MudManagement.Server.Models.mud_quantity_wswn", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("uuid()");

                    b.Property<string>("chanliang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("chanlv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("wushuiliang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("mud_quantity_wswn");
                });
#pragma warning restore 612, 618
        }
    }
}
